<a href="https://colab.research.google.com/github/milnico/masterAI4HU/blob/main/Lezione2_functions_svolta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Functions**

Why Functions?
The purpose of today’s class is to introduce the basics of writing and running Python functions.
Repeating code is painful.
It is also hard to distinguish between the same code repeated three times and three different computations.
It is easy to find a mistake in one copy of a section of code and forget to fix it in the other copies.

Functions are extremely useful for writing complex programs:


1.   They divide complex operations into a combination of simpler steps.
2.   They make programs easier to read and debug by abstracting out frequently repeated code.




a function



*   Takes as input one or more arguments.
*   Computes a new value, a string or a number.
*   Returns the value, so that it can be assigned to a variable or output.

Let’s recall this with a built-in function:

In [ ]:
nums = [2,4,5,6,7,12,34]
len(nums) 

7


**A Function to Compute the Area of a Circle**


In mathematics, many functions are given as formulas. You might write a function to calculate the area of a circle as

a(r)=πr2

In [ ]:
def area_circle(radius):
    pi = 3.14159
    area = pi * radius**2
    return area

a = area_circle(1)
print(a)
print('A circle with radius 2 has area {:.2f}'.format(area_circle(2)))
r = 75.1
a = area_circle(r)
print("A circle with radius {:.2f} has area {:.2f}".format(r,a))

3.14159
A circle with radius 2 has area 12.57
A circle with radius 75.10 has area 17718.60


What does Python do when we run this code?


Reads the keyword def and notes that a function is being defined.

The line that starts with def is called the function header.
Reads the rest of the function definition, checking its syntax.

Notes the end of the definition when the unindented code is reached.

Sees the function call inside the assignment statement

a = area_circle(1)
at what’s known as the “top level” or “main level” of execution and

Jumps back up to the function
Assigns 1 to the parameter radius.
Runs the code inside the function using radius as a variable inside the function.
Returns the result of the calculation back to the top level and assigns the value 3.14159 to the variable a.
Repeats the process of running the function at the second print(), this time with the parameter value 2 and therefore a new value for radius inside the function.

Repeats the process of running the function right after we reassign a, this time with parameter value 75.1 taken from the variable r.

In [ ]:
x = 2
y = 6*x**2 + 3*x + 2
print y



In [ ]:
def f(x):
    return 6*x**2 + 3*x + 2

y = f(2)
print y

In [ ]:
# Define our 3 functions
def my_function():
    print("Hello From My Function!")

def my_function_with_args(username, greeting):
    print("Hello, %s, From My Function!, I wish you %s"%(username, greeting))

def sum_two_numbers(x, y):
    return x + y

def expand_number(x):
    y = x + 10
    z = x + 20
    k = x + 30 
    return y,z,k

# print(a simple greeting)
my_function()

#prints - "Hello, John Doe, From My Function!, I wish you a great year!"
my_function_with_args("John Doe", "a great year!")

# after this line x will hold the value 3!
x = sum_two_numbers(1,2)
y,z,k = expand_number(12)
a,b,c = expand_number(12)
print(y,z,k)

Hello From My Function!
Hello, John Doe, From My Function!, I wish you a great year!
22 32 42


In [ ]:
def max_of_two( x, y ):
    if x > y:
        return x
    return y
def max_of_three( x, y, z ):
    return max_of_two( x, max_of_two( y, z ) )


print(max_of_three(3, 6, -5))

val1=3
val2=33
y = max_of_two(val1,val2)
print(y)

6
33


Write a Python function to sum all the numbers in a list.



In [ ]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total

nums = [8, 2, 3, 0, 7]
print(sum(nums))

20


Write a Python function to multiply all the numbers in a list.


In [ ]:
def multiply(numbers):  
    total = 1
    for x in numbers:
        total *= x  
    return total  
print(multiply((8, 2, 3, -1, 7)))

Write a Python program to reverse a string.



In [ ]:
def string_reverse(str1):

    rstr1 = ''
    index = len(str1)
    while index > 0:
        rstr1 += str1[ index - 1 ]
        index = index - 1
    return rstr1
    
print(string_reverse('1234abcd'))

dcba4321


In [ ]:
s = '1234abcd'
print(s[::-1])

dcba4321



Write a Python program to count how many numbers are between two integers


In [ ]:
def func(x,y):
  count = 0
  #for,while 

  return count

val1 = 12
val2 = 134
print(func())

TypeError: ignored

Write a Python function to create and print a list where the values are square of numbers between 1 and 30 (both included).


In [ ]:

def printValues():
	l = list()
	for i in range(1,21):
		l.append(i**2)
	print(l)
		
printValues()

Write a Python function to check whether a number is even and store it in a new array.



In [ ]:
def is_even_num(l):
    enum = []
    for n in l:
        if n % 2 == 0:
            enum.append(n)
    return enum
print(is_even_num([1, 2, 3, 4, 5, 6, 7, 8, 9]))

[2, 4, 6, 8]


Write a Python program to count the number of even and odd numbers from a series of numbers.



In [ ]:
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9) # Declaring the tuple
count_odd = 0
count_even = 0
for x in numbers:
        if not x % 2:
    	     count_even+=1
        else:
    	     count_odd+=1
print("Number of even numbers :",count_even)
print("Number of odd numbers :",count_odd)

Write a Python program to get the Fibonacci series between 0 to 50.



In [ ]:
x,y=0,1

while y<50:
    print(y)
    x,y = y,x+y